### ISSUE TITLE
[POC] Catalog Views and integration with Service Manager

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#442]
**Description**

Provide new UI for BTP Operator in the Busola where users can see Service Catalog. For now it could be separate application, if installed in the Kyma cluster should already work. In the future probably it will be a part of the btp-manager module.

**Reason**

We want to make `BTP Operator` user's lives easier and more convenient where they can see all of the available services in the Busola and then just provision some of them.

**AC**

- [x] 1) Direct integration with the Service Manager
  - [x] 1.1) User can use default credentials  + can select secret from any namespace (SM credentials are from different SA and then could see different instances and service offerings)
https://github.com/kyma-project/btp-manager/pull/655 https://github.com/kyma-project/btp-manager/pull/674 https://github.com/kyma-project/btp-manager/pull/703
  - [x] 1.2) user can see a list of all service offerings from Service Manager from given SA (SM credentials are bound to given SA)
 https://github.com/kyma-project/btp-manager/pull/717
  - [x] 1.3) User can see a list of all existing instances from Service Manager from given SA (SM credentials are bound to given SA) https://github.com/kyma-project/btp-manager/pull/742, https://github.com/kyma-project/btp-manager/pull/735, https://github.com/kyma-project/btp-manager/pull/746 https://github.com/kyma-project/btp-manager/pull/758
  - [x] 1.4) User can create a service binding on Service Manager side which results as a secret in the selected namespace in the Kyma environment https://github.com/kyma-project/btp-manager/pull/735 https://github.com/kyma-project/btp-manager/pull/757
  - [x] 1.5) User can delete a service binding on Service Manager side which invalidates given secret (probably we need to delete corresponding secret) https://github.com/kyma-project/btp-manager/pull/757 https://github.com/kyma-project/btp-manager/pull/772
- [ ] 2) New BTP Operator UI in the Busola
  - [ ] 2.1) check with Busola team, on how to embed our own web page (We should have a view in the namespace + in the overview taking into account all namespaces data)

- [ ] Think in future of making it mobile - friendly

**Links**

- check smctl what calls are executed
- https://github.com/Peripli/service-manager
- https://help.sap.com/docs/service-manager/sap-service-manager/sap-service-manager

**Comment by PK85** [comment]
Reference sharing:
```
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: kyma-demo-instance-123
  namespace: develope
spec:
  serviceOfferingName: xsuaa
  servicePlanName: reference-instance
  parameters:
    referenced_instance_id: <shared service id>
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: kyma-demo-binding-123
  namespace: develope
spec:
  serviceInstanceName: kyma-demo-instance-123
```

**Comment by szwedm** [comment]
### Meeting notes and current arrangements (3.04.24)
**Arrangements:**
- support operations as in Service Manager
- create REST API similar to Service Manager API (OSBAPI)
- allow to connect Service Instances and Service Bindings from Service Manager to the cluster (custom resources in the cluster should reflect instances and bindings in SM)

**Limitations:**
- Service Manager context is limited to the scope of SAP BTP service operator client provided during Kyma environment provisioning

**Future ideas:**
- allow update of the cluster ID

**Comment by szwedm** [comment]
SAP BTP service operator recognises the following secrets for service instances:
-  default secret named `sap-btp-service-operator` in the centrally managed namespace (`kyma-system`)
- secret for a different subaccount mapped to a namespace in the cluster with namespace's name as a prefix in the secret's name `<namespace-name>-sap-btp-service-operator` in the centrally managed namespace (`kyma-system`)
- secrets named `sap-btp-service-operator` in other namespaces mapped to different subaccounts
- arbitrarily named secret in the centrally managed namespace (`kyma-system`) connected to a different subaccount pointed in the ServiceInstance `btpAccessCredentialsSecret` field in the spec

**Comment by szwedm** [comment]
PR introducing SecretProvider which fetches secrets with credentials for Service Manager:
https://github.com/kyma-project/btp-manager/pull/655

**Comment by szwedm** [comment]
UI PR: https://github.com/kyma-project/btp-manager/pull/649

**Comment by szwedm** [comment]
Adding Service Manager client: https://github.com/kyma-project/btp-manager/pull/674

**Comment by szwedm** [comment]
Unit test for SM client service offerings: https://github.com/kyma-project/btp-manager/pull/703

**Comment by szwedm** [comment]
> * Marketplace: ServiceOffering details + plans details Backend (Marcin)
Done in https://github.com/kyma-project/btp-manager/pull/717

**Comment by szwedm** [comment]
> * Marketplace: Create CRUD Service Instances  Backend (Marcin)

Done in: https://github.com/kyma-project/btp-manager/pull/742

**Comment by szwedm** [comment]
Service Bindings in SM client and Service Instances in API:
https://github.com/kyma-project/btp-manager/pull/735

**Comment by szwedm** [comment]
To do (as of 16.07.24):
- API: create, update, delete Service Instances
- API: list, delete Service Bindings
- API: tests
- Frontend: Service Instances
- Frontend: Service Bindings

**Comment by szwedm** [comment]
Service Bindings API: https://github.com/kyma-project/btp-manager/pull/757

**Comment by szwedm** [comment]
Service Instances API: https://github.com/kyma-project/btp-manager/pull/758

**Comment by szwedm** [comment]
Service Bindings API extension and tests: https://github.com/kyma-project/btp-manager/pull/772

**Comment by szwedm** [comment]
Meeting notes 31.07
- allow to set secret's name and namescape,
- if secret's name is missing, use name from Service Binding. Allow user to provide proposed default value for secret's name (e.g. SB's name + random characters),
- send empty values for clusterid, namespace, k8sname when creating SI/SB,
- display the available secret with its name for Service Binding. If the secret is missing, let the user know and allow to create it in any namespace,
- document questions to CIS team whether there is a way to update context (clusterid, namespace) for existing SIs and SBs (apparently it looks like created SI in K8s cluster cannot change the namespace without deletion of actual service instance).

**Comment by PK85** [comment]
Meeting notes 6.08.2024:

**Comment by ralikio** [comment]
I have discovered a trouble some behaviour: If a service binding with the same name `binding` (just an example name that does not matter in the example) for both binding and secret exists then creating another service binding with the following request fails but binding is created despite the API error:

```
{
name: "binding-new-name"
secret_name: "binding"
secret_namespace: "default"
service_instance_id: "872fe846-569e-4e54-98de-04983e8ea194"
}
```

**Comment by szwedm** [comment]
> I have discovered a troublesome behaviour: If a service binding with the same name `binding` (just an example name that does not matter in the example) for both binding and secret exists then creating another service binding with the following request fails but binding is created despite the API error:
> 
> ```
> {
> name: "binding-new-name"
> secret_name: "binding"
> secret_namespace: "default"
> service_instance_id: "872fe846-569e-4e54-98de-04983e8ea194"
> }
> ```

PR with the fix: https://github.com/kyma-project/btp-manager/pull/826

**Comment by PK85** [comment]
Testing results:
1) When adding new service binding, both name and secret name should have random suffix added. Right now only Secret name has it.
![Image](https://github.com/user-attachments/assets/ff5f62af-5cc9-4343-aa0d-849542f0e581)

**Comment by PK85** [comment]
How to demo:
1) show 3 credentials in the Kyma cluster, two from SA_1 and one from SA_2 (show new UI, Busola and BTP Cockpit)
2) add new entitlement to one of the SA and show new UI that marketplace is extended with new offering (classes and plans)
3) show how to create SI
4) show how to create SB and secret in the given namespace
5) explain how thet looks like in the BTP Cockpit Service instances view (how to find which SM instance was used)
