### ISSUE TITLE
Enable users to customize BTP Operator secret and configMap

### ISSUE THREAD

**Issue by PK85** [kyma-project/btp-manager#901]
**Description**

We will allow to modify and keep user modifications in the btp-manager-secret.

**Reason**

Users wants to migrate btp-operator resources and configurations from one k8s cluster into new Kyma cluster.

**AC**:
- [x] 1) support label on our BTP Manager's secret `sap-btp-manager` to skip reconciliation. Restore the reconciliation when the secret is removed.
  - [x] 1.1) In the BTP Manager's Plutono add dashboard about number of skipped, and be able to see a list of ShootName from those skipped ones.
-  PR: https://github.com/kyma-project/kyma-environment-broker/pull/1532
- [x] 2) if `sap-btp-manager` secret is changed, immediately reconcile btp-operator
  - [x] 2.1) apply changed Service Manager crednetials (keys: **clientid**, **clientsecret**, **tokenurl**, **sm_url**) to `sap-btp-service-operator` secret,
  - [x] 2.2) apply changed cluster ID (key: **cluster_id**) to `sap-btp-operator-config` configmap,
  - [x] 2.3) apply added/changed credentials namespace (key: **credentials_namespace**) to `sap-btp-operator-config` configmap by updating **RELEASE_NAMESPACE** and **MANAGEMENT_NAMESPACE** in the configmap
  - [x] 2.4) ensure `sap-btp-operator-clusterid` secret contains the correct cluster ID,
  - [x] 2.5) ensure the changes are visible in SAP BTP service operator's pod (restart the pod to update the environment variables).
- PR: https://github.com/kyma-project/btp-manager/pull/971
- [x] 3) E2E integration test
- Issue: https://github.com/kyma-project/btp-manager/issues/921
- PR: https://github.com/kyma-project/btp-manager/pull/935 
- [x] 4) docs: [Customizing the Default Credentials and Access](https://help.sap.com/docs/btp/sap-business-technology-platform/customizing-default-credentials-and-access?&version=Cloud)
- [x] 5) RNs: [SAP BTP Operator module: Update to version 1.2.0](https://help.sap.com/whats-new/cf0cb2cb149647329b5d02aa96303f56?Valid_as_Of=2025-02-28:2025-02-28&locale=en-US&version=Cloud)

Agreed label name:
- `kyma-project.io/skip-reconciliation: 'true'`

NOTE!:
- I changed manually CLUSTER ID in our secret, then config map was having it but still instances were created with previous previous CLUSTER ID, see code: https://github.com/SAP/sap-btp-service-operator/blob/9cebc45aded4d8b58396f913720168b0d1307f73/main.go#L208

Progress:
- we should be able to release on fast about 20.02.2025
- some bugs found in the sap btp service operator

**Comment by szwedm** [comment]
> **AC**:
> ...
> * [x]  3) E2E integration test, ticket: [End-to-end (e2e) integration test for customizing BTP Manager input secret #921](https://github.com/kyma-project/btp-manager/issues/921)

PR with the e2e test: https://github.com/kyma-project/btp-manager/pull/935

**Comment by szwedm** [comment]
@ukff see the following code to understand `management_namespace` config:
https://github.com/SAP/sap-btp-service-operator/blob/cca53330710b7c662001ac10e35f91016c27887d/internal/config/config.go#L19
https://github.com/SAP/sap-btp-service-operator/blob/cca53330710b7c662001ac10e35f91016c27887d/internal/utils/sm_utils.go#L19

**Comment by szwedm** [comment]
> If User will change **cluster_id** field in `sap-btp-manager` Secret, then btp-manager will force re-creation of `sap-btp-operator-clusterid` by deleting old one and restarting operator deployment `sap-btp-operator-controller-manager`. To newly created secret will be inserted value from `sap-btp-manager` Secret. Also value will be added/modified in `sap-btp-operator-config` ConfigMap.

Are you sure about the order of resources handling and values insertion?

> If User will add/modify field **management_namespace** in `sap-btp-manager` Secret, then, `sap-btp-service-operator` Secret will be moved to corresponding namespace, if namespace is not present, it will be created Also value will be added/modified in `sap-btp-operator-config` ConfigMap.

When `management_namespace` environment variable change will be visible in the controller in the pod?

> Secret `sap-btp-operator-clusterid` is always in default namespace.

Which namespace is default namespace?

**Comment by jaroslaw-pieszka** [comment]
Could you specify all the relevant keys (in secrets and in the config map)?
```
  MANAGEMENT_NAMESPACE: kyma-system
  RELEASE_NAMESPACE: kyma-system
  management_namespace: kuma-system
```

**Comment by szwedm** [comment]
# Issue investigation and insights

## SAP BTP service operator

Configuration resources for SAP BTP service operator controllers 
a) `sap-btp-operator-config` ConfigMap created in the chart's release namespace. Keys and values are passed as envs to the container.
```json
{
  "ALLOW_CLUSTER_ACCESS"
  "CLUSTER_ID"
  "ENABLE_LIMITED_CACHE"
  "MANAGEMENT_NAMESPACE"
  "RELEASE_NAMESPACE"
}
```

`MANAGEMENT_NAMESPACE` indicates the namespace name for Secrets referenced in Service Instances and Secrets with the name containing a prefix of namespace of the Service Instance.
`RELEASE_NAMESPACE` holds the chart's release namespace name.

Firstly, SAP BTP service operator searches for Secrets in `MANAGEMENT_NAMESPACE`. If there are no Secrets in `MANAGEMENT_NAMESPACE` and in Service Instance's namespace, then it searches for cluster default Secret in `RELEASE_NAMESPACE` as a fallback option.
Ref: https://github.com/SAP/sap-btp-service-operator/blob/1c3ea5a14cf48a4f015ace32a5ea76ae77b20b10/internal/utils/sm_utils.go#L19

b) `sap-btp-operator-clusterid` Secret is created by SAP BTP service operator in the namespace indicated by `RELEASE_NAMESPACE` value. Key and value are passed as env to the container. The Secret is not removed on SAP BTP service operator deletion.
```json
{
  "INITIAL_CLUSTER_ID"
}
```

c) `sap-btp-service-operator` Secret is the default secret for communication with Service Manager, it is created in the chart's release namespace. SAP BTP service operator resorts to this Secret as a fallback option. Keys and values are read dynamically when required.
```json
{
  "clientid"
  "clientsecret"
  "cluster_id"
  "sm_url"
  "tokenurl"
}
```

## BTP Manager

Currently, BTP Manager creates all resources in the namespace indicated by `ChartNamespace` variable, which by default is `kyma-system`. This namespace becomes SAP BTP service operator chart's release namespace, so `RELEASE_NAMESPACE` in `sap-btp-operator-config` ConfigMap holds the same value. The same value is set in `MANAGEMENT_NAMESPACE`, accordingly to the [chart's template](https://github.com/SAP/sap-btp-service-operator/blob/1c3ea5a14cf48a4f015ace32a5ea76ae77b20b10/sapbtp-operator-charts/templates/configmap.yml#L26).

Adding `kyma-project.io/skip-reconciliation: "true"` label in `sap-btp-manager` Secret allows to skip the Secret's reconciliation performed by Kyma Environment Broker. This allows to keep Secret's data as user want it.

`sap-btp-manager` is an input Secret for BTP Manager. Data from the secret is copied to `sap-btp-service-operator` Secret and `sap-btp-operator-config` ConfigMap, both resources are created in `kyma-system` namespace. Secret's keys created by Kyma Environment Broker:
```json
{
  "clientid"
  "clientsecret"
  "cluster_id"
  "sm_url"
  "tokenurl"
}
```
`management_namespace` is an extra field which can be added to the Secret when it is not reconciled.

Changing `cluster_id` or `management_namespace` must result in SAP BTP service operator's pod restart as a last step in the changes processing flow since the values are retrieved from environment variables. Additionally, `cluster_id` change requires deletion of existing `sap-btp-operator-clusterid` Secret prior to the pod deletion.

User changes will be reflected in the resources applied by BTP Manager, `sap-btp-service-operator` Secret, `sap-btp-operator-config` ConfigMap, and in `sap-btp-operator-clusterid` Secret, all created in `kyma-system` namespace. All other resources (namespaces, secrets) required by the changes should be provided by the user.

**Comment by szwedm** [comment]
### BTP Manager behavior on `management_namespace` change proposal
SAP BTP service operator uses `management_namespace` for secrets referenced in a Service Instance's spec and secrets with the Service Instance's namespace prefix in the secret's name. Adding/Changing `management_namespace` in `sap-btp-manager` secret should just set the namespace for SAP BTP service operator. The change should not affect the resources in the namespace. User should take care of Kubernetes resources required by the change, meaning that user is responsible for namespaces and secrets management.

**Comment by szwedm** [comment]
We need to decide whether `management_namespace` should mean the same for BTP Manager and SAP BTP service operator. If changing `management_namespace` in `sap-btp-manager` secret should also change the namespace for SAP BTP service operator's default secret, namely `sap-btp-service-operator` secret in `RELEASE_NAMESPACE` namespace, then `management_namespace` for BTP Manager would be a completely different property than it is for SAP BTP service operator.

**Comment by szwedm** [comment]
Documentation PR: https://github.com/kyma-project/btp-manager/pull/933

**Comment by PK85** [comment]
E2E testing by me, findings:
1) I simulated scenario where btp-manager-secret and sap-btp-operator config map had same proper clusterID, but sap-btp-operator-clusterID secret had old value and sap-btp-operator controller pod was in forever CrashLoopBackOff. 
- Solution: Marcin has applied secret-clusterID to be checked before reconciliation resources
- Drawback: still if pod was in CrashLoopBackOff user will need to wait since k8s will restart a pod. Could be fixed as week, to be decided.
2) When providing not existing credentials_namespace, BTPOperator CR goes into Error. When user create namespaces, users need to wait for next BTP manager controller reconciliation, around 15 min. Could be fixed

**Comment by szwedm** [comment]
PR introducing the feature: https://github.com/kyma-project/btp-manager/pull/971

**Comment by IwonaLanger** [comment]
Publication request for the publication of the doc on the Help Portal: https://jira.tools.sap/browse/NGPDOC-5427

**Comment by IwonaLanger** [comment]
[Customizing the Default Credentials and Access](https://help.sap.com/docs/btp/sap-business-technology-platform/customizing-default-credentials-and-access?&version=Cloud) published. [Preconfigured Credentials and Access](https://help.sap.com/docs/btp/sap-business-technology-platform/preconfigured-credentials-and-access?&version=Cloud) and [SAP BTP Operator Module](https://help.sap.com/docs/btp/sap-business-technology-platform/sap-btp-operator-module?&version=Cloud) updated accordingly.

**Comment by IwonaLanger** [comment]
RN publication requested: https://jira.tools.sap/browse/NGPDOC-5439
